### ISSUE TITLE
(Front) Produktai

### ISSUE THREAD

**Issue by ErnestasZ** [ErnestasZ/Atsiskaitymas_2#18]
Produktu sarasas
Produktu paieska ir filtracija
Produkto kiekis (galimybe pasirinkti)
Produkto isidejimas i krepseli
produkto atsiliepimai (isvedimas)
produkto bendras ivertinimas
Kainos uz vnt, bendra, kaina su nuolaida jei User turi

Pasitikrinti su Backend del bendru funkciju

**Comment by Koffe4ka** [comment]
Produktu sarasas +
Produktu rusiavimas +
Produkto atsiliepimai (isvedimas) +
Produkto bendras ivertinimas + 

**Produktu paieska ir filtracija** 
_Produkto paiešką galiu pabandyti padaryti_

**Cia jau krepselio funkcijos, tai reikia laukti, kol bus padarytas krepselis**
_Produkto kiekis (galimybe pasirinkti)
Produkto isidejimas i krepseli_

**Cia irgi priklauso nuo kitų duomenų, tai kol nebus prisijunges vartotojas, tol ir kainų nematysim**

_Kainos uz vnt, bendra, kaina su nuolaida jei User turi_
